version: '3.8'

services:
    php:
        container_name: php8
        build: php8
        ports:
            - "9000:8000"
        volumes:
            -   ./project:/var/www/html

    mysql:
        image: 'mysql:8.0'
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=app
            - MYSQL_USER=admin
            - MYSQL_PASSWORD=admin
        volumes:
            - db-data:/var/lib/mysql
        ports:
            - "5432"
volumes:
    db-data: